ALTER TABLE product
    ADD rating INT NULL;

ALTER TABLE product
    MODIFY rating INT NOT NULL;

ALTER TABLE category
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE jt_user
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE mentor
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE product
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE st_user
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE student
    MODIFY id BIGINT AUTO_INCREMENT;

INSERT INTO -----